<?php
/**
 * Kaira Presets — generated PHP equivalents of the MCP-server presets.
 *
 * DO NOT EDIT — generated by scripts/sync-presets.js
 *
 * Regenerate with:  node scripts/sync-presets.js
 *
 * @package Kaira
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Get the base identity prompt with the trigger token inserted.
 *
 * @param string $trigger The LoRA trigger token.
 * @return string
 */
function kaira_get_base_prompt( string $trigger ): string {
	return str_replace( '{trigger}', $trigger, 'A photorealistic portrait of {trigger}, a woman in her mid-to-late twenties with an ethnically ambiguous appearance — she could be Mediterranean, Latin, Middle Eastern, or mixed. Dark hair, warm skin tone, striking features. She is always alone in the frame. The style is candid editorial photography — she looks caught in a moment, not posing. Dark and warm color grading, rich shadows, warm highlights, slightly desaturated. The image should feel like a film still, not social media content.' );
}

/**
 * Get the negative prompt applied to all generations.
 *
 * @return string
 */
function kaira_get_negative_prompt(): string {
	return 'cartoon, anime, illustration, painting, watercolor, sketch, deformed, disfigured, blurry, low quality, text, watermark, logo, multiple people, group photo, bright saturated Instagram filter';
}

/**
 * Get all available scene presets.
 *
 * @return array<string, array{description: string, scene: string}>
 */
function kaira_get_presets(): array {
	return array(
		'mykonos_pool' => array(
			'description' => 'Infinity pool overlooking the Aegean, white Cycladic architecture, golden hour',
			'scene'       => 'Infinity pool overlooking the Aegean Sea, white Cycladic architecture in the background, golden hour light, wearing a swimsuit or flowing dress',
		),
		'paris_night' => array(
			'description' => 'Parisian street at night, elegant evening outfit',
			'scene'       => 'Parisian street at night, warm streetlamp glow, elegant evening outfit, café or bridge in background',
		),
		'paris_cafe' => array(
			'description' => 'Seated at a Parisian café terrace, daytime chic casual',
			'scene'       => 'Seated at a Parisian café terrace, espresso or wine on table, daytime, wearing chic casual',
		),
		'bali_sunset' => array(
			'description' => 'Tropical sunset with jungle or rice terraces',
			'scene'       => 'Tropical sunset, lush jungle or rice terraces, flowing fabric, warm golden light',
		),
		'dubai_skyline' => array(
			'description' => 'Modern cityscape at dusk, sleek fashion',
			'scene'       => 'Modern cityscape at dusk, luxurious setting, sleek fashion, city lights beginning to glow',
		),
		'tulum_beach' => array(
			'description' => 'Caribbean beach at dawn, bohemian luxury',
			'scene'       => 'Caribbean beach at dawn, soft morning light, bohemian luxury style, ruins or palm trees',
		),
		'amalfi_coast' => array(
			'description' => 'Colorful Italian coastal village, Mediterranean light',
			'scene'       => 'Colorful Italian coastal village, Mediterranean light, sun hat and summer dress, lemon groves or terraces',
		),
		'gym_fitness' => array(
			'description' => 'High-end gym, athletic wear, dynamic pose',
			'scene'       => 'High-end gym or studio, athletic wear, dynamic mid-movement pose, dramatic lighting',
		),
		'high_fashion' => array(
			'description' => 'Studio or urban editorial, magazine-quality',
			'scene'       => 'Studio or urban editorial setting, high-fashion outfit, strong directional lighting, magazine-quality composition',
		),
		'hotel_luxury' => array(
			'description' => 'Luxury hotel interior, elegant attire',
			'scene'       => 'Luxury hotel interior — lobby, suite, or terrace — elegant attire, warm ambient lighting',
		),
		'restaurant' => array(
			'description' => 'Upscale restaurant or bar, evening candid feel',
			'scene'       => 'Upscale restaurant or bar setting, evening lighting, cocktail or wine, candid mid-conversation feel',
		),
		'winter' => array(
			'description' => 'Cold-weather destination, cozy luxury winter outfit',
			'scene'       => 'Cold-weather destination, cozy luxury winter outfit, snow or misty mountains, warm vs cold contrast',
		),
	);
}

/**
 * Assemble a complete Kaira image prompt from parts.
 *
 * Mirrors the MCP server's buildKairaPrompt() logic: base prompt first,
 * then preset scene (if provided), then custom scene description — all
 * joined with ". ".
 *
 * @param string      $trigger           The LoRA trigger token.
 * @param string|null $preset_key        Preset key (optional).
 * @param string|null $scene_description Custom scene description (optional).
 * @return string
 */
function kaira_build_prompt( string $trigger, ?string $preset_key = null, ?string $scene_description = null ): string {
	$parts = array( kaira_get_base_prompt( $trigger ) );

	if ( $preset_key ) {
		$presets = kaira_get_presets();
		if ( isset( $presets[ $preset_key ] ) ) {
			$parts[] = $presets[ $preset_key ]['scene'];
		}
	}

	if ( $scene_description ) {
		$parts[] = $scene_description;
	}

	return implode( '. ', $parts );
}
