<?php
/**
 * Kaira Presets — generated PHP equivalents of the MCP-server presets.
 *
 * DO NOT EDIT — generated by scripts/sync-presets.js
 *
 * Regenerate with:  node scripts/sync-presets.js
 *
 * @package Kaira
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Get the base identity prompt with the trigger token inserted.
 *
 * @param string $trigger The LoRA trigger token.
 * @return string
 */
function kaira_get_base_prompt( string $trigger = 'KAIRA' ): string {
	return str_replace( '{trigger}', $trigger, 'A candid photograph of {trigger}, a woman in her mid-to-late twenties with an ethnically ambiguous appearance — she could be Mediterranean, Latin, Middle Eastern, or mixed. Dark hair, warm skin tone, striking features. She is always alone in the frame. Shot on Canon EOS R5 with 85mm f/1.4 lens, natural depth of field. Visible skin texture and natural pores, subtle under-eye shadows, flyaway hair strands caught by wind. Real fabric weight and natural wrinkles in clothing. The style is candid editorial photography — caught mid-moment, not posing for camera. Dark and warm color grading, rich shadows, warm highlights, slightly desaturated. Slight film grain, subtle sensor noise. The image should feel like an unretouched frame from a 35mm film scan, not social media content.' );
}

/**
 * Get the negative prompt applied to all generations.
 *
 * @return string
 */
function kaira_get_negative_prompt(): string {
	return 'cartoon, anime, illustration, painting, watercolor, sketch, deformed, disfigured, blurry, low quality, text, watermark, logo, multiple people, group photo, bright saturated Instagram filter, airbrushed skin, smooth skin, plastic skin, poreless skin, beauty filter, over-processed, HDR, mannequin, wax figure, CGI, 3D render, perfect symmetry, overly sharp, hyper-detailed, studio backdrop';
}

/**
 * Get all available scene presets.
 *
 * @return array<string, array{description: string, scene: string}>
 */
function kaira_get_presets(): array {
	return array(
		'mykonos_pool' => array(
			'description' => 'Infinity pool overlooking the Aegean, white Cycladic architecture, golden hour',
			'scene'       => 'Infinity pool overlooking the Aegean Sea, white Cycladic architecture in the background, golden hour light, wearing a swimsuit or flowing dress, leaning on poolside railing, sunlight catching water droplets on skin',
		),
		'paris_night' => array(
			'description' => 'Parisian street at night, elegant evening outfit',
			'scene'       => 'Parisian street at night, warm streetlamp glow, elegant evening outfit, café or bridge in background, mid-stride crossing street, streetlamp casting long shadow behind her',
		),
		'paris_cafe' => array(
			'description' => 'Seated at a Parisian café terrace, daytime chic casual',
			'scene'       => 'Seated at a Parisian café terrace, espresso or wine on table, daytime, wearing chic casual, glancing sideways at something off-camera, one hand around espresso cup',
		),
		'bali_sunset' => array(
			'description' => 'Tropical sunset with jungle or rice terraces',
			'scene'       => 'Tropical sunset, lush jungle or rice terraces, flowing fabric, warm golden light, walking barefoot on a stone path, hand brushing tall grass',
		),
		'dubai_skyline' => array(
			'description' => 'Modern cityscape at dusk, sleek fashion',
			'scene'       => 'Modern cityscape at dusk, luxurious setting, sleek fashion, city lights beginning to glow, standing at a balcony railing, wind pulling at her clothes and hair',
		),
		'tulum_beach' => array(
			'description' => 'Caribbean beach at dawn, bohemian luxury',
			'scene'       => 'Caribbean beach at dawn, soft morning light, bohemian luxury style, ruins or palm trees, walking along waterline, wet sand underfoot, hair blown across face',
		),
		'amalfi_coast' => array(
			'description' => 'Colorful Italian coastal village, Mediterranean light',
			'scene'       => 'Colorful Italian coastal village, Mediterranean light, sun hat and summer dress, lemon groves or terraces, paused on stone steps, adjusting sun hat with one hand',
		),
		'gym_fitness' => array(
			'description' => 'High-end gym, athletic wear, dynamic pose',
			'scene'       => 'High-end gym or studio, athletic wear, dynamic mid-movement pose, dramatic lighting, mid-rep with visible exertion, slight perspiration, focused expression',
		),
		'high_fashion' => array(
			'description' => 'Studio or urban editorial, magazine-quality',
			'scene'       => 'Studio or urban editorial setting, high-fashion outfit, strong directional lighting, magazine-quality composition, turning to look over her shoulder, coat caught mid-swing',
		),
		'hotel_luxury' => array(
			'description' => 'Luxury hotel interior, elegant attire',
			'scene'       => 'Luxury hotel interior — lobby, suite, or terrace — elegant attire, warm ambient lighting, seated on chair arm, one shoe half-off, relaxed unguarded moment',
		),
		'restaurant' => array(
			'description' => 'Upscale restaurant or bar, evening candid feel',
			'scene'       => 'Upscale restaurant or bar setting, evening lighting, cocktail or wine, candid mid-conversation feel, leaning forward mid-laugh, candlelight reflected in her eyes',
		),
		'winter' => array(
			'description' => 'Cold-weather destination, cozy luxury winter outfit',
			'scene'       => 'Cold-weather destination, cozy luxury winter outfit, snow or misty mountains, warm vs cold contrast, hands wrapped around a warm mug, breath visible in cold air',
		),
	);
}

/**
 * Assemble a complete Kaira image prompt from parts.
 *
 * Mirrors the MCP server's buildKairaPrompt() logic: base prompt first,
 * then preset scene (if provided), then custom scene description — all
 * joined with ". ".
 *
 * @param string      $trigger           The LoRA trigger token.
 * @param string|null $preset_key        Preset key (optional).
 * @param string|null $scene_description Custom scene description (optional).
 * @return string
 */
function kaira_build_prompt( string $trigger, ?string $preset_key = null, ?string $scene_description = null ): string {
	$parts = array( kaira_get_base_prompt( $trigger ) );

	if ( $preset_key ) {
		$presets = kaira_get_presets();
		if ( isset( $presets[ $preset_key ] ) ) {
			$parts[] = $presets[ $preset_key ]['scene'];
		}
	}

	if ( $scene_description ) {
		$parts[] = $scene_description;
	}

	return implode( '. ', $parts );
}
