#!/usr/bin/env node
/**
 * sync-presets.js
 *
 * Reads the canonical Kaira presets from wp-mcp-server/prompts/kaira-presets.js
 * and generates kaira-theme/inc/kaira-presets-generated.php so the WordPress
 * theme always stays in sync with the MCP server definitions.
 *
 * Usage:  node scripts/sync-presets.js
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolve paths relative to the repo root (one level up from scripts/).
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

// Import the canonical source of truth.
const { KAIRA_BASE_PROMPT, KAIRA_NEGATIVE_PROMPT, KAIRA_PRESETS } = await import(
  resolve(repoRoot, 'wp-mcp-server/prompts/kaira-presets.js')
);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Escape a string for use inside PHP single quotes.
 * Single quotes become \' and existing backslashes become \\.
 */
function phpEscape(str) {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Indent every line of `text` by `depth` tabs.
 */
function indent(text, depth = 1) {
  const prefix = '\t'.repeat(depth);
  return text
    .split('\n')
    .map((line) => (line.trim() === '' ? '' : prefix + line))
    .join('\n');
}

// ---------------------------------------------------------------------------
// Build the presets PHP array literal
// ---------------------------------------------------------------------------

function buildPresetsPhp() {
  const entries = Object.entries(KAIRA_PRESETS).map(([key, preset]) => {
    return [
      `'${phpEscape(key)}' => array(`,
      `\t'description' => '${phpEscape(preset.description)}',`,
      `\t'scene'       => '${phpEscape(preset.scene)}',`,
      `),`,
    ].join('\n');
  });

  return entries.map((entry) => indent(entry, 2)).join('\n');
}

// ---------------------------------------------------------------------------
// Assemble full PHP file
// ---------------------------------------------------------------------------

const php = `<?php
/**
 * Kaira Presets — generated PHP equivalents of the MCP-server presets.
 *
 * DO NOT EDIT — generated by scripts/sync-presets.js
 *
 * Regenerate with:  node scripts/sync-presets.js
 *
 * @package Kaira
 */

if ( ! defined( 'ABSPATH' ) ) {
\texit;
}

/**
 * Get the base identity prompt with the trigger token inserted.
 *
 * @param string $trigger The LoRA trigger token.
 * @return string
 */
function kaira_get_base_prompt( string $trigger = 'KAIRA' ): string {
\treturn str_replace( '{trigger}', $trigger, '${phpEscape(KAIRA_BASE_PROMPT)}' );
}

/**
 * Get the negative prompt applied to all generations.
 *
 * @return string
 */
function kaira_get_negative_prompt(): string {
\treturn '${phpEscape(KAIRA_NEGATIVE_PROMPT)}';
}

/**
 * Get all available scene presets.
 *
 * @return array<string, array{description: string, scene: string}>
 */
function kaira_get_presets(): array {
\treturn array(
${buildPresetsPhp()}
\t);
}

/**
 * Assemble a complete Kaira image prompt from parts.
 *
 * Mirrors the MCP server's buildKairaPrompt() logic: base prompt first,
 * then preset scene (if provided), then custom scene description — all
 * joined with ". ".
 *
 * @param string      $trigger           The LoRA trigger token.
 * @param string|null $preset_key        Preset key (optional).
 * @param string|null $scene_description Custom scene description (optional).
 * @return string
 */
function kaira_build_prompt( string $trigger, ?string $preset_key = null, ?string $scene_description = null ): string {
\t$parts = array( kaira_get_base_prompt( $trigger ) );

\tif ( $preset_key ) {
\t\t$presets = kaira_get_presets();
\t\tif ( isset( $presets[ $preset_key ] ) ) {
\t\t\t$parts[] = $presets[ $preset_key ]['scene'];
\t\t}
\t}

\tif ( $scene_description ) {
\t\t$parts[] = $scene_description;
\t}

\treturn implode( '. ', $parts );
}
`;

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

const outPath = resolve(repoRoot, 'kaira-theme/inc/kaira-presets-generated.php');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, php, 'utf-8');

console.log(`Generated ${outPath}`);
